
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbczwpspubzejrypljnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiY3p3cHNwdWJ6ZWpyeXBsam53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTg3NDcsImV4cCI6MjA1NjgzNDc0N30.ihZ686WTGOVFD7YF0yNrOBbTuMerQvlbSqFfxetut0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
